P_NEIGHBORHOOD_UP = 0
P_NEIGHBORHOOD_DOWN = 1
P_NEIGHBORHOOD_RIGHT = 2
P_NEIGHBORHOOD_LEFT = 3
P_NEIGHBORHOOD_DIST_UP = 4
P_NEIGHBORHOOD_DIST_DOWN = 5
P_NEIGHBORHOOD_DIST_RIGHT = 6
P_NEIGHBORHOOD_DIST_LEFT= 7
P_PLAYER_X = 8
P_PLAYER_Y = 9
P_COMMAND_CENTER_X =10
P_COMMAND_CENTER_Y = 11
P_AGENT_X = 12
P_AGENT_Y = 13
P_CAN_FIRE = 14
P_HEALTH = 15
O_NOTHING = 0
O_UNBREAKABLE = 1
O_BRICK = 2
O_COMMAND_CENTER= 3
O_PLAYER = 4
O_SHELL = 5
O_OTHER = 6

D_COMBAT=000

A_NOTHING=0
A_UP=1
A_DOWN=2
A_RIGHT=3
A_LEFT=4

C_TOLERANCIA_MOVIMIENTO=-0.25
C_EXPLO=0.6