NOTHING = 0
MOVE_UP = 1
MOVE_DOWN = 2
MOVE_LEFT = 3
MOVE_RIGHT = 4

actions = {
    "NOTHING": NOTHING,
    "MOVE_UP": MOVE_UP,
    "MOVE_DOWN": MOVE_DOWN,
    "MOVE_LEFT": MOVE_LEFT,
    "MOVE_RIGHT": MOVE_RIGHT
}

NEIGHBORHOOD_UP = 0
NEIGHBORHOOD_DOWN = 1
NEIGHBORHOOD_RIGHT = 2
NEIGHBORHOOD_LEFT = 3
NEIGHBORHOOD_DIST_UP = 4
NEIGHBORHOOD_DIST_DOWN = 5
NEIGHBORHOOD_DIST_RIGHT = 6
NEIGHBORHOOD_DIST_LEFT = 7
PLAYER_X = 8
PLAYER_Y = 9
COMMAND_CENTER_X = 10
COMMAND_CENTER_Y = 11
AGENT_X = 12
AGENT_Y = 13
CAN_FIRE = 14
HEALTH = 15

sensors = {
    "NEIGHBORHOOD_UP": NEIGHBORHOOD_UP,
    "NEIGHBORHOOD_DOWN": NEIGHBORHOOD_DOWN,
    "NEIGHBORHOOD_RIGHT": NEIGHBORHOOD_RIGHT,
    "NEIGHBORHOOD_LEFT": NEIGHBORHOOD_LEFT,
    "NEIGHBORHOOD_DIST_UP": NEIGHBORHOOD_DIST_UP,
    "NEIGHBORHOOD_DIST_DOWN": NEIGHBORHOOD_DIST_DOWN,
    "NEIGHBORHOOD_DIST_RIGHT": NEIGHBORHOOD_DIST_RIGHT,
    "NEIGHBORHOOD_DIST_LEFT": NEIGHBORHOOD_DIST_LEFT,
    "PLAYER_X": PLAYER_X,
    "PLAYER_Y": PLAYER_Y,
    "COMMAND_CENTER_X": COMMAND_CENTER_X,
    "COMMAND_CENTER_Y": COMMAND_CENTER_Y,
    "AGENT_X": AGENT_X,
    "AGENT_Y": AGENT_Y,
    "CAN_FIRE": CAN_FIRE,
    "HEALTH": HEALTH
}

NOTHING = 0
UNBREAKABLE = 1
BRICK = 2
COMMAND_CENTER = 3
PLAYER = 4
SHELL = 5
OTHER = 6

objects = {
    "NOTHING": NOTHING,
    "UNBREAKABLE": UNBREAKABLE,
    "BRICK": BRICK,
    "COMMAND_CENTER": COMMAND_CENTER,
    "PLAYER": PLAYER,
    "SHELL": SHELL,
    "OTHER": OTHER
}